[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12.9", features=["blocking", "json"]}
serde = {version= "1.0", features=["derive"]}
serde_json = {version = "1.0"}
colored = {version = "2.0"}
dotenv = "0.15"